sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 6
addons:
  ssh_known_hosts: api.devents.noders.com
before_install:
- openssl aes-256-cbc -K $encrypted_5ae61cbbaac1_key -iv $encrypted_5ae61cbbaac1_iv
  -in secrets.tar.enc -out secrets.tar -d
before_deploy:
- tar -xvf secrets.tar
- echo $TRAVIS_BUILD_DIR
- ls -al
- npm run build
- mv $TRAVIS_BUILD_DIR/env.prod.json $TRAVIS_BUILD_DIR/build/env/env.prod.json
- tar czf deploy.tar.gz $TRAVIS_BUILD_DIR/build
- eval "$(ssh-agent -s)"
- mv $TRAVIS_BUILD_DIR/devents_prod_api_key /tmp/devents_prod_api_key
- chmod 600 /tmp/devents_prod_api_key
- ssh-add /tmp/devents_prod_api_key
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
after_deploy:
- echo "--------- AFTER DEPLOY ---------"
after_script:
- echo "--------- AFTER SCRIPT ---------"
dd:
- openssl aes-256-cbc -K $encrypted_5ae61cbbaac1_key -iv $encrypted_5ae61cbbaac1_iv
  -in env.prod.json.enc -out ./src/env/env.prod.json -d
